### ISSUE TITLE
dropInventory loop called at the end of the timer

### ISSUE THREAD

**Issue by Dreaming-Codes** [Globox1997/Revive#5]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.19

### Mod Version

1.0.5

### Describe the Issue

I am attempting to develop an add-on in which, instead of blocking the revive button, you instantly respawn. However, I have encountered a problem. Once the timer ends, Lnet/minecraft/entity/LivingEntity;dropInventory()V is called in a loop. Grave mods aren't generally affected since they check if you have any items in your inventory. Since your items have just been removed due to the previous call, this doesn't occur. But, I suspect that this could create issues with some other mods.

### latest.log

[02:06:06] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[02:06:06] [main/INFO] (FabricLoader) Loading 55 mods:
	- cloth-config 8.3.103
	- common-protection-api 1.0.0
	- fabric-api 0.60.0+1.19.2
	- fabric-api-base 0.4.11+e62f51a390
	- fabric-api-lookup-api-v1 1.6.9+9ff28f4090
	- fabric-biome-api-v1 9.0.17+aeb40ebe90
	- fabric-blockrenderlayer-v1 1.1.20+aeb40ebe90
	- fabric-client-tags-api-v1 1.0.1+b35fea8390
	- fabric-command-api-v2 2.1.7+0c17ea9690
	- fabric-content-registries-v0 3.2.3+aeb40ebe90
	- fabric-convention-tags-v1 1.1.1+7cd20a1490
	- fabric-crash-report-info-v1 0.2.5+aeb40ebe90
	- fabric-data-generation-api-v1 5.1.8+a680b9b490
	- fabric-dimensions-v1 2.1.30+aeb40ebe90
	- fabric-entity-events-v1 1.4.18+9ff28f4090
	- fabric-events-interaction-v0 0.4.28+aeb40ebe90
	- fabric-game-rule-api-v1 1.0.21+aeb40ebe90
	- fabric-gametest-api-v1 1.0.35+e62f51a390
	- fabric-item-api-v1 1.5.7+35a03c4390
	- fabric-item-groups-v0 0.3.28+aeb40ebe90
	- fabric-key-binding-api-v1 1.0.20+aeb40ebe90
	- fabric-lifecycle-events-v1 2.1.2+aeb40ebe90
	- fabric-loot-api-v2 1.1.3+83a8659290
	- fabric-message-api-v1 5.0.3+176380a290
	- fabric-mining-level-api-v1 2.1.14+33fbc73890
	- fabric-models-v0 0.3.17+aeb40ebe90
	- fabric-networking-api-v1 1.2.4+5eb68ef290
	- fabric-object-builder-api-v1 4.0.11+aeb40ebe90
	- fabric-particles-v1 1.0.10+aeb40ebe90
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.9.24+aeb40ebe90
	- fabric-renderer-api-v1 1.0.10+aeb40ebe90
	- fabric-renderer-indigo 0.6.12+aeb40ebe90
	- fabric-rendering-data-attachment-v1 0.3.14+aeb40ebe90
	- fabric-rendering-fluids-v1 3.0.7+aeb40ebe90
	- fabric-rendering-v1 1.10.16+aeb40ebe90
	- fabric-resource-conditions-api-v1 2.0.11+e62f51a390
	- fabric-resource-loader-v0 0.6.1+aeb40ebe90
	- fabric-screen-api-v1 1.0.26+f05effaf90
	- fabric-screen-handler-api-v1 1.2.13+9ff28f4090
	- fabric-textures-v0 1.0.20+aeb40ebe90
	- fabric-transfer-api-v1 2.0.11+83a8659290
	- fabric-transitive-access-wideners-v1 1.3.0+42d99c3290
	- fabricloader 0.14.9
	- hologram-api 0.2.2+1.19
	- java 17
	- minecraft 1.19.2
	- packet_tweaker 0.3.0+1.18.2
	- placeholder-api 2.0.0-pre.1+1.19.2
	- polymer 0.2.17+1.19.2
	- polymer-registry-sync-manipulator 0.0.3+1.19.2
	- revive 1.0.5
	- server_translations_api 1.4.18+1.19.2
	- sgui 1.1.5+1.19.1
	- universal-graves 2.1.3+1.19.2
[02:06:06] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/dreamingcodes/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/c1dc27696aa4006e492c2485c9ccbcb26045a971/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[02:06:06] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[02:06:06] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_17
[02:06:07] [main/WARN] (FileUtil) Configuration conflict: there is more than one oshi.properties file on the classpath
[02:06:07] [main/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[02:06:08] [main/INFO] (Minecraft) Building optimized datafixer
[02:06:12] [Render thread/INFO] (Minecraft) Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[02:06:13] [Render thread/ERROR] (fabric-screen-api-v1) Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?]
	at net.minecraft.client.MinecraftClient.createUserApiService(MinecraftClient.java:711) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:431) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:205) [minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [minecraft-project-@-merged-named.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?]
	... 10 more
[02:06:13] [Render thread/INFO] (fabric-screen-api-v1) Setting user: Player624
[02:06:14] [Render thread/INFO] (Indigo) [Indigo] Registering Indigo renderer!
[02:06:15] [Render thread/INFO] (fabric-screen-api-v1) Backend library: LWJGL version 3.3.1 SNAPSHOT
[02:06:17] [Worker-Main-20/ERROR] (Minecraft) Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.client.util.ProfileKeys.fetchKeyPair(ProfileKeys.java:130) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.util.ProfileKeys.method_44291(ProfileKeys.java:69) ~[minecraft-project-@-merged-named.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[02:06:17] [Render thread/INFO] (Minecraft) Reloading ResourceManager: Default, Fabric Mods (Fabric Item Groups (v0), Fabric Rendering (v1), Fabric Object Builder API (v1), Fabric Registry Sync (v0), Polymer (Core), Fabric Networking API (v1), Fabric Entity Events (v1), Fabric Particles (v1), Fabric Mining Level API (v1), Fabric Dimensions API (v1), Fabric Resource Loader (v0), Fabric Screen Handler API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Textures (v0), Universal Graves, Fabric Message API (v1), Fabric Command API (v2), Fabric Events Interaction (v0), Fabric Data Generation API (v1), Fabric Rendering Data Attachment (v1), Fabric Game Rule API (v1), Fabric API, Fabric API Lookup API (v1), Fabric Crash Report Info (v1), Revive, Fabric Transitive Access Wideners (v1), Fabric Resource Conditions API (v1), Fabric Screen API (v1), Fabric Content Registries (v0), Fabric Loader, Fabric API Base, Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Rendering Fluids (v1), Fabric Renderer - Indigo, Fabric Models (v0), Fabric Renderer API (v1), Fabric Biome API (v1), Fabric Key Binding API (v1), Fabric Game Test API (v1), Fabric Client Tags, Cloth Config v8, Fabric Item API (v1), Fabric Transfer API (v1), Fabric Convention Tags)
[02:06:17] [Realms Notification Availability checker #1/INFO] (Minecraft) Could not authorize you against Realms server: Invalid session id
[02:06:20] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:item.goat_horn.play
[02:06:20] [Render thread/WARN] (Minecraft) Missing sound for event: minecraft:entity.goat.screaming.horn_break
[02:06:20] [Render thread/INFO] (Minecraft) OpenAL initialized on device JACK Default
[02:06:20] [Render thread/INFO] (Minecraft) Sound engine started
[02:06:20] [Render thread/INFO] (Minecraft) Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[02:06:20] [Render thread/INFO] (Minecraft) Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[02:06:20] [Render thread/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[02:06:20] [Render thread/INFO] (Minecraft) Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[02:06:20] [Render thread/INFO] (Minecraft) Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[02:06:20] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[02:06:20] [Render thread/INFO] (Minecraft) Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[02:06:22] [Render thread/WARN] (Minecraft) Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[02:06:22] [Render thread/INFO] (Minecraft) Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[02:06:22] [Render thread/INFO] (Minecraft) Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[02:06:22] [Render thread/INFO] (Minecraft) Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[02:06:26] [Worker-Bootstrap-16/INFO] (Minecraft) 4283 Datafixer optimizations took 17708 milliseconds
[02:06:27] [Render thread/INFO] (FabricRegistrySync) [fabric-registry-sync] Loaded registry data [file 1/4]
[02:06:27] [Render thread/INFO] (Minecraft) Loaded 7 recipes
[02:06:27] [Render thread/INFO] (Minecraft) Loaded 1179 advancements
[02:06:27] [ForkJoinPool.commonPool-worker-1/INFO] (ServerTranslations) Loaded 5483 translation keys
[02:06:28] [Worker-Main-30/ERROR] (Minecraft) Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at net.minecraft.client.util.ProfileKeys.fetchKeyPair(ProfileKeys.java:130) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.client.util.ProfileKeys.method_44291(ProfileKeys.java:69) ~[minecraft-project-@-merged-named.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[02:06:28] [Render thread/INFO] (BiomeModificationImpl) Applied 0 biome modifications to 0 of 63 new biomes in 2.477 ms
[02:06:29] [Server thread/INFO] (Minecraft) Starting integrated minecraft server version 1.19.2
[02:06:29] [Server thread/INFO] (Minecraft) Generating keypair
[02:06:29] [Server thread/INFO] (Minecraft) Preparing start region for dimension minecraft:overworld
[02:06:30] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[02:06:30] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[02:06:30] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[02:06:30] [Render thread/INFO] (Minecraft) Preparing spawn area: 0%
[02:06:31] [Render thread/INFO] (Minecraft) Preparing spawn area: 58%
[02:06:31] [Render thread/INFO] (Minecraft) Time elapsed: 2211 ms
[02:06:31] [Server thread/INFO] (Minecraft) Changing view distance to 12, from 10
[02:06:31] [Server thread/INFO] (Minecraft) Changing simulation distance to 12, from 0
[02:06:32] [Server thread/INFO] (Minecraft) Player624[local:E:c7f02b6b] logged in with entity id 191 at (318.33887599449497, 70.0, 252.29005691135268)
[02:06:32] [Server thread/INFO] (Polymer) Partial sync for Player624 took 20.51 ms
[02:06:32] [Server thread/INFO] (Minecraft) Player624 joined the game
[02:06:35] [Render thread/INFO] (Minecraft) Loaded 3 advancements
[02:06:35] [Server thread/INFO] (Polymer) Full sync for Player624 took 8.17 ms
[02:06:35] [Render thread/INFO] (Minecraft) [System] [CHAT] Created grave at 318, 70, 252 (Overworld). It will expire in 30m
[02:06:35] [Server thread/WARN] (Minecraft) Can't keep up! Is the server overloaded? Running 2665ms or 53 ticks behind
[02:06:49] [Render thread/INFO] (Minecraft) Loaded 21 advancements
[02:06:57] [Server thread/INFO] (Minecraft) [Player624: Teleported Player624 to 326.300000, 168.000000, 232.766371]
[02:06:57] [Render thread/INFO] (Minecraft) [System] [CHAT] Teleported Player624 to 326.300000, 168.000000, 232.766371
[02:06:58] [Server thread/INFO] (Minecraft) Saving and pausing game...
[02:06:58] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[02:06:58] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[02:06:58] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[02:07:03] [Server thread/INFO] (Minecraft) Player624 fell from a high place
[02:07:03] [Render thread/INFO] (Minecraft) [System] [CHAT] Player624 fell from a high place
[02:07:12] [Server thread/WARN] (Minecraft) Can't keep up! Is the server overloaded? Running 4122ms or 82 ticks behind
[02:07:12] [Render thread/INFO] (Minecraft) [System] [CHAT] Created grave at 326, 68, 232 (Overworld). It will expire in 30m
[02:08:09] [Server thread/WARN] (Minecraft) Can't keep up! Is the server overloaded? Running 41525ms or 830 ticks behind
[02:10:01] [Server thread/INFO] (Minecraft) Saving and pausing game...
[02:10:01] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[02:10:01] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[02:10:01] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[02:11:17] [Server thread/INFO] (Minecraft) Player624 lost connection: Disconnected
[02:11:17] [Server thread/INFO] (Minecraft) Player624 left the game
[02:11:17] [Server thread/INFO] (Minecraft) Stopping singleplayer server as player logged out
[02:11:17] [Server thread/INFO] (Minecraft) Stopping server
[02:11:17] [Server thread/INFO] (Minecraft) Saving players
[02:11:17] [Server thread/INFO] (Minecraft) Saving worlds
[02:11:18] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[02:11:18] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[02:11:18] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[02:11:18] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (New World): All chunks are saved
[02:11:18] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[02:11:18] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[02:11:18] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage: All dimensions are saved

### Do you use any other mods except the required ones?

UniversalGraves

**Comment by Globox1997** [comment]
please contact me on discord :)
